In [1]:
import numpy as np 
import math 
ln10=np.log(10) 
e=math.e

In [2]:
mwceph=np.genfromtxt('datamw_cep2.txt')
m=mwceph[:,5]+0.0075-10+5*np.log(mwceph[:,10])/(ln10)

In [3]:
hostceph=np.genfromtxt('r16 table4.txt')
m2=hostceph[:,2]

In [4]:
lmcceph=np.genfromtxt('r19 table2.txt')
m3=lmcceph[:,5]+0.03

In [5]:
miu=np.array( [29.397,18.477])

In [6]:
sn=np.genfromtxt('r16 table5.txt')
mb=sn[:,2]+sn[:,4]

In [7]:
Y=np.hstack((m,m2,m3,miu,mb))
print(Y.size)

1651


In [8]:
a=np.zeros(51)
for i in range(74):
    if mwceph[i,0]<1:
        a1=np.array([0,mwceph[i,1]-mwceph[i,3],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,mwceph[i,0]-1,0,mwceph[i,9],-5/mwceph[i,10]/ln10,0])
    elif hostceph[i,0]>1:
        a1=np.array([0,mwceph[i,1]-mwceph[i,3],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,mwceph[i,0]-1,mwceph[i,9],-5/mwceph[i,10]/ln10,0])
    i+=1
    a=np.vstack((a,a1))
a=np.delete(a,0,axis=0)


In [9]:

for i in range(251):
    if hostceph[i,0]<10:
        a1=np.array([0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))

In [10]:
for i in range(251,265):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [11]:
for i in range(265,309):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [12]:
for i in range(309,341):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [13]:
for i in range(341,395):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [14]:
for i in range(395,536):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [15]:
for i in range(536,554):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [16]:
for i in range(554,617):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [17]:
for i in range(617,697):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [18]:
for i in range(697,739):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [19]:
for i in range(739,755):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [20]:
for i in range(755,768):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [21]:
for i in range(768,771):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [22]:
for i in range(771,804):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [23]:
for i in range(804,829):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [24]:
for i in range(829,912):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [25]:
for i in range(912,925):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [26]:
for i in range(925,947):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))



In [27]:
for i in range(947,975):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [28]:
for i in range(975,1114):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))


In [29]:
for i in range(1114,1486):
    if hostceph[i,0]<10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,math.log(hostceph[i,0],10)-1,0,hostceph[i,4]-8.824,0,0])
    elif hostceph[i,0]>10:
        a1=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hostceph[i,1],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,math.log(hostceph[i,0],10)-1,hostceph[i,4]-8.824,0,0])
    i+=1
    a=np.vstack((a,a1))

In [30]:
for i in range(70):
    if lmcceph[i,0]<1:
        a1=np.array([lmcceph[i,1]-lmcceph[i,3],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,lmcceph[i,0]-1,0,-0.3,0,0])
    elif lmcceph[i,0]>1:
        a1=np.array([lmcceph[i,1]-lmcceph[i,3],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,lmcceph[i,0]-1,-0.3,0,0])
    i+=1
    a=np.vstack((a,a1))


In [31]:
a2=np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0,0,0,0,0,0,
       0, 0, 1, 0,0, 0, 0, 0, 0, 0, 0])

a4=np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0,0,0,0,0,0,
       0, 0, 0, 0,1, 0, 0, 0, 0, 0, 0])
a=np.vstack((a,a2,a4))


In [32]:
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1]),
a=np.vstack((a,a4))
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))
a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))
a4=np.array([0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))

a4=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0,0, 1])
a=np.vstack((a,a4))




In [33]:
#np.savetxt('a0.txt',a)
#np.savetxt('y0.txt',Y)


In [34]:
error1=np.genfromtxt('datamw_cep2.txt')
e1=error1[:,6]+0.006
e2=(5/ln10)*error1[:,11]/error1[:,10]
e3=0.39*error1[:,2]
e4=0.39*error1[:,4]
error1=e1**2+e2**2+e3**2+e4**2
#error1=e1**2+e2**2
error1

array([0.0052507 , 0.00458237, 0.00400488, 0.00451906, 0.00529096,
       0.00431799, 0.00396618, 0.00536913, 0.00376963, 0.00611259,
       0.00410315, 0.00469499, 0.00542071, 0.00615327, 0.00362998,
       0.00477887, 0.00431756, 0.00473177, 0.00543777, 0.00458567,
       0.00392185, 0.00494587, 0.00418436, 0.00395138, 0.00416986,
       0.00540151, 0.00439078, 0.00667057, 0.0048724 , 0.00400722,
       0.00491649, 0.00532885, 0.00423349, 0.00541889, 0.00429064,
       0.0045616 , 0.00368454, 0.00378912, 0.00501202, 0.00445049,
       0.00381843, 0.00703311, 0.0043212 , 0.00525903, 0.00352782,
       0.00397761, 0.00406603, 0.00481045, 0.00477885, 0.00559133,
       0.00563617, 0.00563984, 0.00551272, 0.00462948, 0.00536981,
       0.00550979, 0.00476263, 0.00475404, 0.00466079, 0.00580854,
       0.00553405, 0.00615473, 0.00550427, 0.00475748, 0.00454526,
       0.0056856 , 0.00571562, 0.0056462 , 0.00478668, 0.00551465,
       0.00570685, 0.00554117, 0.00467886, 0.00661921])

In [35]:
error2=np.genfromtxt('r16 table4.txt')
error2=error2[0:1486,3]
error2=error2**2

In [36]:
error4=np.genfromtxt('r19 table2.txt')
e5=error4[:,6]+0.024
e6=0.39*error4[:,2]
e7=0.39*error4[:,4]
error4=e5**2+0.08**2+e6**2+e7**2
#error4=e5**2
error4

array([0.00830165, 0.00852052, 0.0110313 , 0.00822002, 0.00881435,
       0.00848721, 0.01036887, 0.00935631, 0.00913822, 0.00836064,
       0.01042196, 0.00864931, 0.00967942, 0.0086528 , 0.00924611,
       0.01078064, 0.00836672, 0.01095668, 0.00873761, 0.00925402,
       0.00873153, 0.00864611, 0.00983731, 0.00934672, 0.00904511,
       0.00854642, 0.00846911, 0.00866512, 0.00822134, 0.00874163,
       0.00915161, 0.00947322, 0.00866163, 0.00845861, 0.01122001,
       0.01586634, 0.00863364, 0.00845572, 0.00847367, 0.00884922,
       0.01235105, 0.01236261, 0.0089438 , 0.00946531, 0.00828931,
       0.00893361, 0.00945253, 0.00937593, 0.00902853, 0.00874081,
       0.00947261, 0.00865402, 0.00884131, 0.00830634, 0.00866817,
       0.00978605, 0.00971486, 0.01000587, 0.00893042, 0.00919313,
       0.00840566, 0.00914491, 0.0093103 , 0.00901757, 0.00926893,
       0.00870878, 0.00834102, 0.00883461, 0.00888009, 0.01028431])

In [37]:
error5=np.array([0.032,0.0263])
error5=error5**2
error5

array([0.001024  , 0.00069169])

In [38]:
error6=np.genfromtxt('r16 table5.txt')
error6=(error6[:,1])**2
error6

array([0.013689, 0.015129, 0.013456, 0.015625, 0.013456, 0.020164,
       0.013689, 0.013225, 0.015376, 0.013456, 0.013225, 0.012996,
       0.011881, 0.015376, 0.013225, 0.013225, 0.013225, 0.013225,
       0.012996])

In [39]:
error=np.hstack((error1,error2,error4,error5,error6))
print(error)
error.size

[0.0052507  0.00458237 0.00400488 ... 0.013225   0.013225   0.012996  ]


1651

In [40]:

errorc=np.diag(error)

errorc

array([[0.0052507 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00458237, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00400488, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.013225  , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.013225  ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.012996  ]])

In [41]:
#np.savetxt('error0.txt',errorc)

In [42]:
x=np.linalg.inv((np.transpose(a))@(np.linalg.inv(errorc))@a)@((np.transpose(a))@(np.linalg.inv(errorc))@Y)
x

array([ 4.71318637e-01,  3.75217149e-01,  4.91248136e-01,  5.05013715e-02,
        2.13079723e-01,  3.20020496e-01,  1.78357721e-01,  2.30484320e-01,
        4.70183413e-01,  5.49064543e-02,  9.42823691e-02,  1.00328205e-01,
        3.97799516e-01,  1.01874908e-01,  4.10915530e-01,  2.19109146e-01,
        1.46233721e-01,  1.41693959e-01,  1.88192288e-01,  2.07949571e-01,
        3.27155931e-01,  3.23028545e-01,  2.75334057e-01,  2.90329572e+01,
        3.28830801e+01,  3.26850565e+01,  3.13534680e+01,  3.15112812e+01,
        3.17454918e+01,  3.23954319e+01,  3.24223869e+01,  3.21800022e+01,
        3.19259382e+01,  3.16858501e+01,  3.16448012e+01,  3.09839717e+01,
        3.10676282e+01,  3.17762374e+01,  3.21044876e+01,  3.24567684e+01,
        3.17128883e+01,  3.29424622e+01,  2.93963848e+01,  2.45806431e+01,
        1.84669059e+01, -5.95357853e+00, -3.27474914e+00, -3.17014336e+00,
       -1.82294173e-01, -6.78023999e-04, -1.94278173e+01])

In [43]:
aT=np.transpose(a)

In [44]:
errorinv=np.linalg.inv(errorc)

In [45]:
result=(np.linalg.inv(aT@(errorinv@a)))@(aT@(errorinv@Y))
result

array([ 4.71318637e-01,  3.75217149e-01,  4.91248136e-01,  5.05013715e-02,
        2.13079723e-01,  3.20020496e-01,  1.78357721e-01,  2.30484320e-01,
        4.70183413e-01,  5.49064543e-02,  9.42823691e-02,  1.00328205e-01,
        3.97799516e-01,  1.01874908e-01,  4.10915530e-01,  2.19109146e-01,
        1.46233721e-01,  1.41693959e-01,  1.88192288e-01,  2.07949571e-01,
        3.27155931e-01,  3.23028545e-01,  2.75334057e-01,  2.90329572e+01,
        3.28830801e+01,  3.26850565e+01,  3.13534680e+01,  3.15112812e+01,
        3.17454918e+01,  3.23954319e+01,  3.24223869e+01,  3.21800022e+01,
        3.19259382e+01,  3.16858501e+01,  3.16448012e+01,  3.09839717e+01,
        3.10676282e+01,  3.17762374e+01,  3.21044876e+01,  3.24567684e+01,
        3.17128883e+01,  3.29424622e+01,  2.93963848e+01,  2.45806431e+01,
        1.84669059e+01, -5.95357853e+00, -3.27474914e+00, -3.17014336e+00,
       -1.82294173e-01, -6.78023999e-04, -1.94278173e+01])

In [46]:
# estimate H0
H0=10**((result[50]+0.71273*5+25)/5)
print(H0)

67.16863802963205


In [47]:
chi2=(Y-a@result)@errorinv@(Y-a@result)
chi2

1565.6001657907564

In [48]:
AIC=chi2+102
AIC

1667.6001657907564

In [49]:
BIC=chi2+51*np.log(1651)
BIC

1943.4661244306828